language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit --configuration phpunit.xml --bootstrap vendor/autoload.php

cache:
    directories:
        - vendor
